#!/bin/bash

Uhost="localhost"
Uname="root"
Upawd="1234"
Uinitpj="no"
Uinitdb="no"
Uinitht="no"

while getopts "h:u:p:edi" opt
do
	case $opt in
		 h)
		 	Uhost=$OPTARG;;
		 u)
		 	Uname=$OPTARG;;
		 p)
		 	Upawd=$OPTARG;;
		 e)
		 	Uinitpj="yes";;
		 d)
		 	Uinitdb="yes";;
		 i)
		 	Uinitht="yes";;
		 ?)
			echo "unkonw option"
			exit 1
			;;
	esac
done


if [ $Uinitpj = "yes" ]; then
	echo "initialing project environment."
fi


if [ $Uinitdb = "yes" ]; then
	echo "initialing database with -h$Uhost, -u$Uname, -p$Upawd."
fi


if [ $Uinitht = "yes" ]; then
	echo "initialing index page for each directory."
fi


# run it by
# sh thisfilename  -e -d -h localhost -u root -p 1234

